name: Generate and Deploy Documentation

on:
  push:
    branches:
      - doxygen  # Adjust this to your default branch

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Documentation
      run: doxygen doc/Doxyfile
      
    - name: Upload
	    uses: actions/upload-artifact@v1
	    with:
	      name: doxygen-docs
	      path: web  # Assuming Doxygen outputs HTML docs to web

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web  # Replace with the path to your generated documentation
